### ISSUE TITLE
Not really an issue with the mod itself but I found a light switch not working !

### ISSUE THREAD

**Issue by ShinraSetora** [Xpazeman/tld-house-lights#5]
Hi !
The one on the first floor in the camp office on mystery lac is not working(i added a picture to show which one), so if you ever do an update on the mod maybe you could add it, other than that, the mod is great, awesome job !

![20210307182216_1](https://user-images.githubusercontent.com/58953975/110248950-debfa400-7f73-11eb-9c0f-1f9c17e66ae4.jpg)

**Comment by Xpazeman** [comment]
The mod adds lightswitches automatically by name, so it might be that that lightswitch has a different name and thus isn't recognized by the mod.
If you have Remove Clutter installed, it might also be that the postit is receiving the hover event instead of the switch.
Anyway, I'll check it out and see if ther's something that can be done.
